@startuml

class Vector {
  + Coordinates : double[] {get, set}
  + Dimensions : int {get}
  + add(x : Vector) : Vector
  + subtract(x : Vector) : Vector
  + scalarProduct(x : Vector) : double
  
  
}
class 3DVector extends Vector  {
  + CrossProduct(x : Vector) : Vector
  
}

class Matrix {
  + Coordinates : double[][] {get, set}
  + Rows : int {get}
  + Columns : int {get}
  + ScalarProduct(y : double) : Matrix
  + Transpose() : Matrix
  + Inverse() : Matrix
  + Determinant() : double
  + Trace() : double
  + EigenValues() : double[]
  + EigenVectors() : Vector[]
}

class Transformation {
  # TransformationMatrix : Matrix {get, set}
  + Transform(v : Vector) : Vector
}

interface IRenderer {
  + Render(v : Vector) : void
  + Render(m : Matrix) : void
}

Transformation *-- Matrix : uses
Transformation ..> Vector : transforms
Renderer ..> Vector : renders
Renderer ..> Matrix : renders

@enduml