@startuml

class Vector {
  + Coordinates : double[] {get, set}
  + Dimensions : int {get}
  + add(x : Vector) : Vector
  + subtract(x : Vector) : Vector
  + scalarProduct(x : Vector) : double
  
  
}
class 3DVector extends Vector  {
  + Coordinates : double[] {get, set}
  + Dimensions : int {get}
  + add(x : Vector) : Vector
  + subtract(x : Vector) : Vector
  + scalarProduct(x : Vector) : double
  + crossProduct(x : Vector) : Vector
  
}

class Matrix {
  + Coordinates : double[][] {get, set}
  + Rows : int {get}
  + Columns : int {get}
  + scalarProduct(y : double) : Matrix
  + transpose() : Matrix
  + inverse() : Matrix
  + determinant() : double
  + trace() : double
  + eigenValues() : double[]
  + eigenVectors() : Vector[]
}

abstract class Transformation {
  # TransformationMatrix : Matrix {get, set}
  + apply(v : Vector) : Vector
}

interface Renderer {
  + render(v : Vector) : void
  + render(m : Matrix) : void
}

Transformation *-- Matrix : uses
Transformation ..> Vector : transforms
Renderer ..> Vector : renders
Renderer ..> Matrix : renders

@enduml